"""
Auto-generated by WaAct Compiler
DO NOT EDIT THIS FILE MANUALLY
"""

from typing import Dict, Any
from llm_client import invoke_function  # 需要实现 LLM 客户端


def step_1_compute_vector_similarity_threshold():
    """Auto-generated module"""
    return access_log_retention_days, cache_expiration_minutes, code_analysis_time_s, code_line_threshold, debug_log_retention_days, error_log_retention_days, graph_response_time_s, kg_neighbor_hops, legal_docs_count, max_concurrent_requests, medical_docs_count, qps_alert_threshold, response_time_95th_alert, tech_docs_count, total_response_time_s, user_priority_admin, user_priority_normal, user_priority_vip, vector_dim, vector_response_time_ms, vector_similarity_threshold, vector_top_k_results_high, vector_top_k_results_low


async def step_2_vector_search(query_type, similarity, vector_similarity_threshold, vector_top_k_results_high, vector_top_k_results_low):
    """Auto-generated module"""
    if query_type == "simple_fact":
        if similarity > vector_similarity_threshold:
            results = await invoke_function('vector_search', top_k=vector_top_k_results_high)
        elif similarity <= vector_similarity_threshold:
            results = await invoke_function('rerank_model')
            results = await invoke_function('vector_search', top_k=vector_top_k_results_low)
        else:
            results = await invoke_function('hybrid_search')
    return results


async def step_3_intent_decomposition(cache_expiration_minutes, kg_neighbor_hops, query, query_type):
    """Auto-generated module"""
    if query_type == "complex_reasoning":
        intents = await invoke_function('intent_decomposition', query=query)
        graph_results = await invoke_function('graph_search', hops=kg_neighbor_hops)
        if graph_results.found:
            results = graph_results.entities_and_relations
        else:
            results = await invoke_function('full_graph_search')
        await invoke_function('cache_results', results=results, expiration_minutes=cache_expiration_minutes)
    return graph_results, intents, results


async def step_4_static_code_analysis(code_line_threshold, query, query_type):
    """Auto-generated module"""
    if query_type == "code_analysis":
        if code_lines > code_line_threshold:
            analysis = await invoke_function('static_code_analysis', query=query)
        else:
            analysis = await invoke_function('semantic_code_analysis', query=query)
            documentation = await invoke_function('generate_code_documentation', analysis=analysis)
        results = analysis
    return analysis, code_lines, documentation, results


async def step_5_strong_reasoning_model(query, user_feedback):
    """Auto-generated module"""
    if user_feedback == "regenerate":
        results = await invoke_function('strong_reasoning_model', query=query)
    return results


async def step_6_escalate_to_human_review(negative_feedback_count, query):
    """Auto-generated module"""
    if negative_feedback_count >= 3:
        await invoke_function('escalate_to_human_review', query=query)
    return None


async def step_7_reject_service(query):
    """Auto-generated module"""
    if "sensitive_word" in query:
        await invoke_function('reject_service')
        await invoke_function('log_security_incident')
    return None


async def step_8_require_user_authentication(query):
    """Auto-generated module"""
    if "financial" in query:
        await invoke_function('require_user_authentication')
    return None


async def step_9_degrade_service(response_time, total_response_time_s):
    """Auto-generated module"""
    if response_time > total_response_time_s:
        await invoke_function('degrade_service')
    return None


def step_10_upload_log_to_central_system(error_log_retention_days):
    """Auto-generated module"""
    await invoke_function('upload_log_to_central_system', log_type="error", retention_days=error_log_retention_days)
    return None


def step_11_upload_log_to_central_system(access_log_retention_days):
    """Auto-generated module"""
    await invoke_function('upload_log_to_central_system', log_type="access", retention_days=access_log_retention_days)
    return None


def step_12_upload_log_to_central_system(debug_log_retention_days):
    """Auto-generated module"""
    await invoke_function('upload_log_to_central_system', log_type="debug", retention_days=debug_log_retention_days)
    return None


async def step_13_trigger_alert(qps, qps_alert_threshold):
    """Auto-generated module"""
    if qps < qps_alert_threshold:
        await invoke_function('trigger_alert', _Low_QPS_=_Low_QPS_)
    return None


async def step_14_trigger_scaling(response_time_95th, response_time_95th_alert):
    """Auto-generated module"""
    if response_time_95th > response_time_95th_alert:
        await invoke_function('trigger_scaling')
    return None


def step_15_compute_results(results):
    """Auto-generated module"""
    return results


async def main_workflow(input_params: dict):
    """
    主工作流 - 自动生成
    
    Args:
        input_params: 包含 ['negative_feedback_count', 'qps', 'query', 'query_type', 'response_time', 'response_time_95th', 'similarity', 'user_feedback'] 的字典
    
    Returns:
        执行结果上下文
    """
    # 初始化上下文
    ctx = input_params.copy()

    # Module 1: step_1_compute_vector_similarity_threshold
    ctx["access_log_retention_days"], ctx["cache_expiration_minutes"], ctx["code_analysis_time_s"], ctx["code_line_threshold"], ctx["debug_log_retention_days"], ctx["error_log_retention_days"], ctx["graph_response_time_s"], ctx["kg_neighbor_hops"], ctx["legal_docs_count"], ctx["max_concurrent_requests"], ctx["medical_docs_count"], ctx["qps_alert_threshold"], ctx["response_time_95th_alert"], ctx["tech_docs_count"], ctx["total_response_time_s"], ctx["user_priority_admin"], ctx["user_priority_normal"], ctx["user_priority_vip"], ctx["vector_dim"], ctx["vector_response_time_ms"], ctx["vector_similarity_threshold"], ctx["vector_top_k_results_high"], ctx["vector_top_k_results_low"] = step_1_compute_vector_similarity_threshold()

    # Module 2: step_2_vector_search
    ctx["results"] = await step_2_vector_search(ctx.get("query_type"), ctx.get("similarity"), ctx.get("vector_similarity_threshold"), ctx.get("vector_top_k_results_high"), ctx.get("vector_top_k_results_low"))

    # Module 3: step_3_intent_decomposition
    ctx["graph_results"], ctx["intents"], ctx["results"] = await step_3_intent_decomposition(ctx.get("cache_expiration_minutes"), ctx.get("kg_neighbor_hops"), ctx.get("query"), ctx.get("query_type"))

    # Module 4: step_4_static_code_analysis
    ctx["analysis"], ctx["code_lines"], ctx["documentation"], ctx["results"] = await step_4_static_code_analysis(ctx.get("code_line_threshold"), ctx.get("query"), ctx.get("query_type"))

    # Module 5: step_5_strong_reasoning_model
    ctx["results"] = await step_5_strong_reasoning_model(ctx.get("query"), ctx.get("user_feedback"))

    # Module 6: step_6_escalate_to_human_review
    await step_6_escalate_to_human_review(ctx.get("negative_feedback_count"), ctx.get("query"))

    # Module 7: step_7_reject_service
    await step_7_reject_service(ctx.get("query"))

    # Module 8: step_8_require_user_authentication
    await step_8_require_user_authentication(ctx.get("query"))

    # Module 9: step_9_degrade_service
    await step_9_degrade_service(ctx.get("response_time"), ctx.get("total_response_time_s"))

    # Module 10: step_10_upload_log_to_central_system
    step_10_upload_log_to_central_system(ctx.get("error_log_retention_days"))

    # Module 11: step_11_upload_log_to_central_system
    step_11_upload_log_to_central_system(ctx.get("access_log_retention_days"))

    # Module 12: step_12_upload_log_to_central_system
    step_12_upload_log_to_central_system(ctx.get("debug_log_retention_days"))

    # Module 13: step_13_trigger_alert
    await step_13_trigger_alert(ctx.get("qps"), ctx.get("qps_alert_threshold"))

    # Module 14: step_14_trigger_scaling
    await step_14_trigger_scaling(ctx.get("response_time_95th"), ctx.get("response_time_95th_alert"))

    # Module 15: step_15_compute_results
    ctx["__results__"] = step_15_compute_results(ctx.get("results"))

    return ctx



if __name__ == "__main__":
    import asyncio
    
    # 测试输入
    test_input = {
        # TODO: 填充实际参数
    }
    
    result = asyncio.run(main_workflow(test_input))
    from logger import info
    info("执行结果:", result)