"""
Auto-generated by WaAct Compiler
DO NOT EDIT THIS FILE MANUALLY
"""

from typing import Dict, Any
from llm_client import invoke_function  # 需要实现 LLM 客户端


def step_1_compute_tech_stack():
    """Auto-generated module"""
    return duration_days, duration_days_2, duration_days_3, tech_stack


async def step_2_vector_search(query_type, similarity):
    """Auto-generated module"""
    if query_type == "simple_fact":
        if similarity > 0.85:
            results = await invoke_function('vector_search', top_k=_3)
        elif similarity <= 0.85:
            results = await invoke_function('rerank_model')
            results = await invoke_function('vector_search', top_k=_5)
        else:
            results = await invoke_function('hybrid_search')
    elif query_type == "complex_reasoning":
        intent = await invoke_function('intent_decomposition')
        if intent   is  not   None:
            kg_results = await invoke_function('graph_search', hops=_2)
            if kg_results   is  not   None:
                return kg_results
            else:
                kg_results = await invoke_function('graph_full_search')
                return kg_results
        else:
            kg_results = await invoke_function('graph_full_search')
            return kg_results
    elif query_type == "code_related":
        code_lines = await invoke_function('count_code_lines')
        if code_lines > 500:
            analysis = await invoke_function('static_analysis')
        elif code_lines <= 500:
            analysis = await invoke_function('semantic_analysis')
            doc = await invoke_function('generate_explanation', analysis=analysis)
            return doc
    else:
        results = await invoke_function('default_search')


async def step_3_strong_model_inference(user_action):
    """Auto-generated module"""
    if user_action == "regenerate":
        response = await invoke_function('strong_model_inference')
        return response


async def step_4_escalate_to_human_review(negative_feedback_count):
    """Auto-generated module"""
    if negative_feedback_count >= 3:
        await invoke_function('escalate_to_human_review')
    return None


async def step_5_reject_service(query, sensitive_words):
    """Auto-generated module"""
    if sensitive_words in query:
        await invoke_function('reject_service')
        await invoke_function('log_to_security')
    return None


async def step_6_secondary_authentication(query):
    """Auto-generated module"""
    if "金融" in query:
        await invoke_function('secondary_authentication')
    return None


async def step_7_degrade_service(response_time):
    """Auto-generated module"""
    if response_time > 3000:
        await invoke_function('degrade_service')
    return None


def step_8_upload_logs(duration_days):
    """Auto-generated module"""
    await invoke_function('upload_logs', log_type="error", retention_days=duration_days)
    return None


def step_9_upload_logs(duration_days_2):
    """Auto-generated module"""
    await invoke_function('upload_logs', log_type="access", retention_days=duration_days_2)
    return None


def step_10_upload_logs(duration_days_3):
    """Auto-generated module"""
    await invoke_function('upload_logs', log_type="debug", retention_days=duration_days_3)
    return None


async def step_11_trigger_alert(qps):
    """Auto-generated module"""
    if qps < 10:
        await invoke_function('trigger_alert')
    return None


async def step_12_trigger_scaling(p95_latency):
    """Auto-generated module"""
    if p95_latency > 3000:
        await invoke_function('trigger_scaling')
    return None


async def main_workflow(input_params: dict):
    """
    主工作流 - 自动生成
    
    Args:
        input_params: 包含 ['negative_feedback_count', 'p95_latency', 'qps', 'query', 'query_type', 'response_time', 'sensitive_words', 'similarity', 'user_action'] 的字典
    
    Returns:
        执行结果上下文
    """
    # 初始化上下文
    ctx = input_params.copy()

    # Module 1: step_1_compute_tech_stack
    ctx["duration_days"], ctx["duration_days_2"], ctx["duration_days_3"], ctx["tech_stack"] = step_1_compute_tech_stack()

    # Module 2: step_2_vector_search
    ctx["__doc__"], ctx["__kg_results__"], ctx["analysis"], ctx["code_lines"], ctx["doc"], ctx["intent"], ctx["kg_results"], ctx["results"] = await step_2_vector_search(ctx.get("query_type"), ctx.get("similarity"))

    # Module 3: step_3_strong_model_inference
    ctx["__response__"], ctx["response"] = await step_3_strong_model_inference(ctx.get("user_action"))

    # Module 4: step_4_escalate_to_human_review
    await step_4_escalate_to_human_review(ctx.get("negative_feedback_count"))

    # Module 5: step_5_reject_service
    await step_5_reject_service(ctx.get("query"), ctx.get("sensitive_words"))

    # Module 6: step_6_secondary_authentication
    await step_6_secondary_authentication(ctx.get("query"))

    # Module 7: step_7_degrade_service
    await step_7_degrade_service(ctx.get("response_time"))

    # Module 8: step_8_upload_logs
    step_8_upload_logs(ctx.get("duration_days"))

    # Module 9: step_9_upload_logs
    step_9_upload_logs(ctx.get("duration_days_2"))

    # Module 10: step_10_upload_logs
    step_10_upload_logs(ctx.get("duration_days_3"))

    # Module 11: step_11_trigger_alert
    await step_11_trigger_alert(ctx.get("qps"))

    # Module 12: step_12_trigger_scaling
    await step_12_trigger_scaling(ctx.get("p95_latency"))

    return ctx



if __name__ == "__main__":
    import asyncio
    
    # 测试输入
    test_input = {
        # TODO: 填充实际参数
    }
    
    result = asyncio.run(main_workflow(test_input))
    from logger import info
    info("执行结果:", result)